In [7]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
import pandas as pd

data = {
    'Weather': ['Sunny', 'Overcast', 'Rainy', 'Sunny', 'Rainy', 'Overcast', 'Sunny', 'Overcast', 'Rainy', 'Sunny'],
    'Temperature': ['Hot', 'Mild', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Hot', 'Mild', 'Cool'],
    'Play': ['No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)

df['Weather'] = df['Weather'].map({'Sunny': 0, 'Overcast': 1, 'Rainy': 2})
df['Temperature'] = df['Temperature'].map({'Hot': 0, 'Mild': 1, 'Cool': 2})
df['Play'] = df['Play'].map({'No': 0, 'Yes': 1})

X = df[['Weather', 'Temperature']]
y = df['Play']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print("Confusion Matrix:")
print(conf_matrix)
print("\nAccuracy:", accuracy)

sample = pd.DataFrame([[1, 1]], columns=['Weather', 'Temperature']) 
prediction = knn.predict(sample)

if prediction[0] == 1:
    print("\nPrediction: The players can play when the weather is overcast and the temperature is mild.")
else:
    print("\nPrediction: The players cannot play when the weather is overcast and the temperature is mild.")


Confusion Matrix:
[[0 1]
 [0 1]]

Accuracy: 0.5

Prediction: The players can play when the weather is overcast and the temperature is mild.


In [9]:
import numpy as np

train_points = np.array([[7, 7], [7, 4], [3, 4], [1, 4]])
train_labels = ['Bad', 'Bad', 'Good', 'Good']

query_point = np.array([3, 7])

distances = np.linalg.norm(train_points - query_point, axis=1)
nearest_indices = distances.argsort()[:3]
nearest_labels = [train_labels[i] for i in nearest_indices]

prediction = max(set(nearest_labels), key=nearest_labels.count)
print("Prediction:", prediction)


Prediction: Good


In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

data = {
    'Name of Exercise': [
        'Push-ups', 'Squats', 'Lunges', 'Burpees', 'Mountain Climbers',
        'Jumping Jacks', 'Bicycle Crunches', 'Ops', 'Pull-ups',
        'Russian Twists', 'Leg Raises', 'Deadlifts', 'Bench Press',
        'Bicep Curls', 'Shoulder Press', 'Calf Raises', 'Tricep Extension'
    ],
    'Sets': [3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 3, 3, 3, 3, 3],
    'Reps': [15, 12, 12, 10, 10, 15, 12, 10, 10, 12, 12, 10, 8, 15, 12, 15, 12],
    'Burns Calories (per 30 min)': [
        220, 250, 235, 280, 290, 220, 230, 220, 250, 210, 220, 240, 230, 215, 225, 210, 200
    ],
    'Target Muscle Group': [
        'Chest', 'Triceps', 'Shoulders', 'Quadriceps', 'Hamstrings', 'Glutes',
        'Hamstrings', 'Glutes', 'Full Body', 'Core', 'Triceps', 'Chest', 'Back', 'Biceps',
        'Deltoids', 'Lower Abs', 'Back'
    ],
    'Difficulty Level': [
        'Intermediate', 'Beginner', 'Beginner', 'Advanced', 'Intermediate',
        'Beginner', 'Intermediate', 'Advanced', 'Intermediate', 'Intermediate',
        'Advanced', 'Intermediate', 'Intermediate', 'Intermediate', 'Beginner',
        'Intermediate', 'Beginner'
    ]
}


df = pd.DataFrame(data)

le = LabelEncoder()
df['Target Muscle Group'] = le.fit_transform(df['Target Muscle Group'])
df['Difficulty Level'] = le.fit_transform(df['Difficulty Level'])

X = df[['Sets', 'Reps', 'Burns Calories (per 30 min)', 'Target Muscle Group']]
y = df['Difficulty Level']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

k = 3
model = KNeighborsClassifier(n_neighbors=k)

model.fit(X_train, y_train)

predicted = model.predict(X_test)
print("Predicted Labels:", predicted)

conf_mat = confusion_matrix(y_test, predicted)
print("Confusion Matrix:")
print(conf_mat)

accuracy = accuracy_score(y_test, predicted)
print("Accuracy:", accuracy)


Predicted Labels: [2 0 2 2]
Confusion Matrix:
[[0 0 0]
 [1 0 1]
 [0 0 2]]
Accuracy: 0.5
